# Generated by Django 5.1.2 on 2024-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersummary',
            name='alert_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
